// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmcgzozzspvrwfpscmyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtY2d6b3p6c3B2cndmcHNjbXl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjA1OTAsImV4cCI6MjA2NzYzNjU5MH0.6IdB_GaC8dpJQ2iBwisbrvLPdPh1zWKLHKfApT07zZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});